"""Content categorization and tagging logic"""

from typing import List


class ContentCategorizer:
    """Categorizes content based on keywords and context"""

    GOOGLE_TRENDS_TAG = "google trends"

    CATEGORY_KEYWORDS = {
        "Sports": [
            "sport",
            "football",
            "soccer",
            "basketball",
            "hockey",
            "nhl",
            "nfl",
            "nba",
            "mlb",
            "tennis",
            "olympic",
            "athlete",
            "baseball",
            "golf",
            "match",
            "game",
            "player",
            "team",
            "championship",
            "tournament",
            "coach",
            "stadium",
            "league",
            "playoff",
            "score",
            "world cup",
            "super bowl",
            "fifa",
            "ufc",
            "boxing",
            "racing",
            "f1",
            "maple leafs",
            "leafs",
            "raptors",
            "oilers",
            "canadiens",
            "habs",
            "canucks",
            "flames",
            "senators",
            "jets",
            "bruins",
            "rangers",
            "penguins",
            "capitals",
            "golden knights",
            "blackhawks",
            "avalanche",
            "panthers",
            "lightning",
            "lakers",
            "warriors",
            "celtics",
            "heat",
            "bulls",
            "knicks",
            "nets",
            "clippers",
            "mavericks",
            "spurs",
            "blue jays",
            "yankees",
            "red sox",
            "dodgers",
            "giants",
            "trade rumors",
            "roster",
            "draft",
            "free agent",
            "signing",
            "waiver",
            "lineup",
            "injury report",
            "starting lineup",
        ],
        "Entertainment": [
            "entertainment",
            "movie",
            "film",
            "music",
            "celebrity",
            "tv",
            "show",
            "series",
            "concert",
            "festival",
            "actor",
            "actress",
            "singer",
            "band",
            "album",
            "grammy",
            "oscar",
            "emmy",
            "hollywood",
            "netflix",
            "disney",
            "marvel",
            "streaming",
            "theatre",
            "broadway",
            "comedy",
            "drama",
            "premiere",
            "trailer",
            "box office",
            "artist",
            "musician",
            "song",
            "songwriter",
            "rapper",
            "rock",
            "pop",
            "country",
            "hip hop",
            "jazz",
            "recording",
            "tour",
            "live show",
            "performance",
            "billboard",
            "chart",
            "snl",
            "saturday night live",
            "late night",
            "talk show",
        ],
        "Technology": [
            "tech",
            "ai",
            "artificial intelligence",
            "machine learning",
            "software",
            "hardware",
            "computer",
            "internet",
            "gadget",
            "robot",
            "cyber",
            "smartphone",
            "app",
            "iphone",
            "android",
            "google",
            "apple",
            "microsoft",
            "meta",
            "tesla",
            "bitcoin",
            "crypto",
            "blockchain",
            "data",
            "cloud",
            "security",
            "hack",
            "innovation",
            "digital",
            "online",
            "social media",
            "twitter",
            "facebook",
        ],
        "Business": [
            "business",
            "finance",
            "stock",
            "market",
            "economy",
            "startup",
            "trade",
            "investment",
            "company",
            "entrepreneur",
            "ceo",
            "revenue",
            "profit",
            "loss",
            "merger",
            "acquisition",
            "bankruptcy",
            "earnings",
            "wall street",
            "nasdaq",
            "dow jones",
            "s&p",
            "inflation",
            "recession",
            "gdp",
            "corporate",
            "industry",
        ],
        "Politics": [
            "politics",
            "government",
            "election",
            "policy",
            "law",
            "president",
            "minister",
            "prime minister",
            "congress",
            "senate",
            "parliament",
            "vote",
            "legislation",
            "democrat",
            "republican",
            "liberal",
            "conservative",
            "campaign",
            "candidate",
            "trudeau",
            "biden",
            "trump",
            "political",
            "federal",
            "provincial",
            "municipal",
        ],
        "Health": [
            "health",
            "medicine",
            "medical",
            "doctor",
            "hospital",
            "wellness",
            "fitness",
            "disease",
            "nutrition",
            "vaccine",
            "covid",
            "pandemic",
            "virus",
            "drug",
            "treatment",
            "patient",
            "mental health",
            "therapy",
            "cancer",
            "diabetes",
            "healthcare",
            "pharmacy",
            "clinic",
            "surgery",
            "diagnosis",
            "symptom",
        ],
        "Science": [
            "science",
            "research",
            "study",
            "scientist",
            "discovery",
            "experiment",
            "nasa",
            "space",
            "climate",
            "environment",
            "physics",
            "chemistry",
            "biology",
            "astronomy",
            "planet",
            "mars",
            "rocket",
            "satellite",
            "laboratory",
        ],
        "World News": [
            "international",
            "global",
            "world",
            "foreign",
            "country",
            "nation",
            "war",
            "conflict",
            "peace",
            "treaty",
            "diplomatic",
            "united nations",
            "eu",
            "europe",
            "asia",
            "africa",
            "middle east",
            "crisis",
            "humanitarian",
        ],
        "Crime": [
            "crime",
            "police",
            "arrest",
            "murder",
            "robbery",
            "theft",
            "fraud",
            "investigation",
            "court",
            "trial",
            "verdict",
            "guilty",
            "innocent",
            "sentence",
            "prison",
            "jail",
            "detective",
            "fbi",
            "rcmp",
            "criminal",
            "suspect",
            "shooting",
        ],
        "Weather": [
            "weather",
            "storm",
            "hurricane",
            "tornado",
            "flood",
            "snow",
            "blizzard",
            "temperature",
            "forecast",
            "climate change",
            "wildfire",
            "drought",
            "rain",
            "wind",
            "cold",
            "heat wave",
            "winter",
            "summer",
        ],
        "Education": [
            "education",
            "school",
            "university",
            "college",
            "student",
            "teacher",
            "professor",
            "learning",
            "curriculum",
            "exam",
            "graduation",
            "tuition",
            "campus",
            "academic",
        ],
        "Lifestyle": [
            "lifestyle",
            "fashion",
            "beauty",
            "travel",
            "food",
            "recipe",
            "restaurant",
            "cooking",
            "style",
            "trend",
            "home",
            "decor",
            "design",
            "wedding",
            "relationship",
        ],
    }

    def categorize_text(self, text: str) -> str:
        """Categorize text based on keywords. Returns best matching category or 'General'.
        Sports and Entertainment keywords get higher priority (1.5x weight).
        """
        text_lower = text.lower()
        scores = dict.fromkeys(self.CATEGORY_KEYWORDS, 0)

        for cat, keywords in self.CATEGORY_KEYWORDS.items():
            weight = 1.5 if cat in ("Sports", "Entertainment") else 1
            for kw in keywords:
                if kw in text_lower:
                    scores[cat] += weight

        best_category = max(scores, key=scores.get)
        return best_category if scores[best_category] > 0 else "General"

    def extract_category(self, entry) -> str:
        """Determine category using keywords in title, description, and tags."""
        title = getattr(entry, "title", "")
        description = (
            getattr(entry, "ht_news_item_snippet", "")
            or getattr(entry, "summary", "")
            or getattr(entry, "description", "")
        )
        tags = []
        if hasattr(entry, "tags"):
            for tag in entry.tags:
                if hasattr(tag, "term"):
                    tags.append(tag.term.lower())
        text = f"{title} {description} {' '.join(tags)}"
        return self.categorize_text(text)

    def extract_tags(self, entry) -> List[str]:
        """Extract tags from entry"""
        tags = ["trending", "canada", self.GOOGLE_TRENDS_TAG]
        if hasattr(entry, "tags"):
            for tag in entry.tags:
                if hasattr(tag, "term"):
                    tags.append(tag.term.lower())
        return list(set(tags))
